apiVersion: v1
kind: ConfigMap
metadata:
  name: filebeat-config
  namespace: skill-ex-demo
data:
  filebeat.yml: |-
    filebeat.inputs:
    - type: container
      paths:
        - /var/log/containers/*.log
      multiline.pattern: '^\['
      multiline.negate: true
      multiline.match: after

    - type: log
      paths:
        - /app/logs/*.log
      multiline.pattern: '^\['
      multiline.negate: true
      multiline.match: after

    processors:
      - add_kubernetes_metadata:
          in_cluster: true

      - drop_event:
          when:
            not:
              equals:
                kubernetes.namespace: "skill-ex-demo"

    output.logstash:
      hosts: ["logstash.skill-ex-demo.svc.cluster.local:5044"]


    setup.kibana:
      host: "http://kibana:5601"
