stages:
  ingest:
    cmd: export PYTHONPATH=$PYTHONPATH:. && ./venv/bin/python microservices/ingestion/run.py
    deps:
      - microservices/ingestion/run.py
      - shared/data/pipeline.py
    outs:
      - job_market.db:
          cache: true
          persist: true

  train:
    cmd: export PYTHONPATH=$PYTHONPATH:. && ./venv/bin/python microservices/model_training/train.py
    deps:
      - job_market.db
      - microservices/model_training/train.py
      - microservices/recommendation_api/engine.py
    metrics:
      - mlruns:
          cache: false
