apiVersion: v1
kind: Service
metadata:
  name: model-training-service
  namespace: skill-ex-demo 
spec:
  selector:
    app: model-training
  ports:
    - protocol: TCP
      port: ?
      targetPort: ?
  type: NodePort