---
- name: Create namespace
  shell: |
    unset http_proxy; unset https_proxy; unset no_proxy;
    kubectl create namespace {{ kube_namespace }} --dry-run=client -o yaml | kubectl apply -f - --validate=false
  # ignore_errors: true

- name: Delete existing model-training pods
  shell: |
    unset http_proxy; unset https_proxy; unset no_proxy;
    kubectl delete pods -l app=model-training -n {{ kube_namespace }} --ignore-not-found=true

- name: Delete existing dashboard pods
  shell: |
    unset http_proxy; unset https_proxy; unset no_proxy;
    kubectl delete pods -l app=dashboard -n {{ kube_namespace }} --ignore-not-found=true

- name: Delete existing mlflow pods
  shell: |
    unset http_proxy; unset https_proxy; unset no_proxy;
    kubectl delete pods -l app=mlflow -n {{ kube_namespace }} --ignore-not-found=true

- name: Delete existing ml-api pods
  shell: |
    unset http_proxy; unset https_proxy; unset no_proxy;
    kubectl delete pods -l app=ml-api -n {{ kube_namespace }} --ignore-not-found=true

- name: Deploy model-training
  shell: |
    unset http_proxy; unset https_proxy; unset no_proxy;
    kubectl apply -f ../k8s/model-training/deployment.yml -n {{ kube_namespace }} 

- name: Deploy dashboard
  shell: |
    unset http_proxy; unset https_proxy; unset no_proxy;
    kubectl apply -f ../k8s/dashboard -n {{ kube_namespace }}

- name: Deploy mlflow
  shell: |
    unset http_proxy; unset https_proxy; unset no_proxy;
    kubectl apply -f ../k8s/mlflow/deployment.yml -n {{ kube_namespace }}

- name: Deploy ml-api
  shell: |
    unset http_proxy; unset https_proxy; unset no_proxy;
    kubectl apply -f ../k8s/ml-api -n {{ kube_namespace }} 

# ELK Deployment
- name: Deploy Elasticsearch
  shell: |
    unset http_proxy; unset https_proxy; unset no_proxy;
    kubectl apply -f ../elk/elasticsearch/ -n {{ kube_namespace }}

- name: Deploy Logstash
  shell: |
    unset http_proxy; unset https_proxy; unset no_proxy;
    kubectl apply -f ../elk/logstash/ -n {{ kube_namespace }} 

- name: Deploy Kibana
  shell: |
    unset http_proxy; unset https_proxy; unset no_proxy;
    kubectl apply -f ../elk/kibana/ -n {{ kube_namespace }}

- name: Deploy Filebeat
  shell: |
    unset http_proxy; unset https_proxy; unset no_proxy;
    kubectl apply -f ../elk/filebeat/ -n {{ kube_namespace }}