apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlflow-deployment
  namespace: skill-ex-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mlflow
  template:
    metadata:
      labels:
        app: mlflow
    spec:
      containers:
        - name: mlflow
          image: anujajose/microservices-mlflow:latest
          envFrom:
            - secretRef:
                name: app-secrets
          ports:
            - containerPort: 5000