apiVersion: v1
kind: ConfigMap
metadata:
  name: logstash-pipeline
  namespace: skill-ex-demo
data:
  logstash.conf: |
    input {
      beats {
        port => 5044
      }
    }

    filter {
      # Updated Grok for Python/Uvicorn logs
      grok {
        match => { "message" => "%{LOGLEVEL:level}:\s+%{GREEDYDATA:log_message}" }
        overwrite => [ "message" ]
      }

      date {
        match => [ "timestamp", "ISO8601" ]
      }
    }

    output {
      elasticsearch {
        hosts => ["http://elasticsearch.skill-ex-demo.svc.cluster.local:9200"]
        index => "logstash-%{+YYYY.MM.dd}"
      }

      stdout { codec => rubydebug }
    }
