services:
  # ingestion:
  #   build:
  #     context: .
  #     dockerfile: ./ingestion/Dockerfile
  #   container_name: ingestion_service
  #   env_file: .env
  #   volumes:
  #     - .:/app
  #   environment:
  #     - PYTHONPATH=/app:/app/ingestion
  #   depends_on:
  #     - ml-api

  mlflow:
    build:
      context: ./mlflow
      dockerfile: Dockerfile
    container_name: mlflow_service
    ports:
      - "5000:5000"
    env_file: .env
    volumes:
      - .:/app
    command: >
      mlflow server 
      --backend-store-uri sqlite:///app/mlflow.db 
      --default-artifact-root s3://amzn-s3-models-bucket/artifacts 
      --host 0.0.0.0

  dashboard:
    build:
      context: .
      dockerfile: ./dashboard/Dockerfile
    container_name: dashboard_service
    ports:
      - "8501:8501"
    volumes:
      - .:/app
    environment:
      - PYTHONPATH=/app:/app/dashboard
    depends_on:
      - ml-api

  ml-api:
    build:
      context: .
      dockerfile: ./ml/Dockerfile
    container_name: ml_api_service
    ports:
      - "8000:8000"
    env_file: .env
    volumes:
      - .:/app
    environment:
      - PYTHONPATH=/app:/app/ml
      - MLFLOW_TRACKING_URI=http://mlflow:5000
      - GIT_PYTHON_REFRESH=quiet
    depends_on:
      - mlflow

  model-training:
    build:
      context: .
      dockerfile: ./model_training/Dockerfile
    container_name: model_training_service
    env_file: .env
    volumes:
      - .:/app
    environment:
      - PYTHONPATH=/app:/app/ml
      - MLFLOW_TRACKING_URI=http://mlflow:5000
    depends_on:
      - mlflow
      - ml-api