services:
  ingestion:
    build:
      context: .
      dockerfile: microservices/ingestion/Dockerfile
    container_name: ingestion_service
    env_file: .env
    volumes:
      - ./microservices/ingestion:/app
      - ./ml/shared:/app/ml/shared
    depends_on:
      - ml-api

  dashboard:
    build:
      context: .
      dockerfile: microservices/dashboard/Dockerfile
    container_name: dashboard_service
    ports:
      - "8501:8501"
    volumes:
      - ./microservices/dashboard:/app
    depends_on:
      - ml-api

  ml-api:
    build:
      context: .
      dockerfile: microservices/ml/Dockerfile
    container_name: ml_api_service
    ports:
      - "8000:8000"
    env_file: .env
    volumes:
      - .:/app  # Maps root to allow access to shared and microservices
    environment:
      - PYTHONPATH=/app